# Generated by Django 5.0 on 2023-12-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_id_todo_user_alter_user_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_content',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_flag',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_title',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
